// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace Hulujan_Iulia_Petruta_proiectNouM
{
    public partial class StudentModel
    {
        /// <summary>
        /// model input class for StudentModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [Range(0, 10, ErrorMessage = "Orele studiate trebuie sa fie intre 0 si 10.")]
            [LoadColumn(0)]
            [ColumnName(@"Hours Studied")]
            public float Hours_Studied { get; set; }

            [Range(0, 100, ErrorMessage = "Scorul anterior trebuie să fie intre 0 si 100.")]
            [LoadColumn(1)]
            [ColumnName(@"Previous Scores")]
            public float Previous_Scores { get; set; }

            [Range(0, 12, ErrorMessage = "Orele de somn trebuie sa fie intre 0 si 12.")]
            [LoadColumn(2)]
            [ColumnName(@"Sleep Hours")]
            public float Sleep_Hours { get; set; }

            [Range(0, 10, ErrorMessage = "Numarul de chestionare trebuie ss fie pozitiv.")]
            [LoadColumn(3)]
            [ColumnName(@"Sample Question Papers Practiced")]
            public float Sample_Question_Papers_Practiced { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Performance Index")]
            public float Performance_Index { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for StudentModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Hours Studied")]
            public float Hours_Studied { get; set; }

            [ColumnName(@"Previous Scores")]
            public float Previous_Scores { get; set; }

            [ColumnName(@"Sleep Hours")]
            public float Sleep_Hours { get; set; }

            [ColumnName(@"Sample Question Papers Practiced")]
            public float Sample_Question_Papers_Practiced { get; set; }

            [ColumnName(@"Performance Index")]
            public float Performance_Index { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("StudentModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
